# Generated by Django 2.1.14 on 2020-10-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=20, verbose_name='学院名称')),
            ],
            options={
                'db_table': 'orm_department',
            },
        ),
        migrations.CreateModel(
            name='Obtain_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('l_l', models.CharField(max_length=50)),
                ('radius', models.CharField(max_length=50)),
                ('postal', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'orm_Obtain_1',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=30, verbose_name='姓名代号')),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='orms.Department')),
            ],
            options={
                'db_table': 'orm_student',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'orm_UserModel',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='0', max_length=1024, verbose_name='姓名代号')),
                ('age', models.CharField(max_length=10, null=True, verbose_name='年龄')),
            ],
        ),
    ]
