# Generated by Django 2.1.14 on 2020-10-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('l_l', models.CharField(max_length=50)),
                ('radius', models.CharField(max_length=50)),
                ('postal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Obtain_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('l_l', models.CharField(max_length=50)),
                ('radius', models.CharField(max_length=50)),
                ('postal', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'orm_Obtain_2',
            },
        ),
    ]
