# Generated by Django 2.1.14 on 2020-10-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orms', '0002_ip_obtain_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
